package core

var BASIC_KEYCODES = []string{
	"KC_NO",
	"KC_TRNS",
	"KC_A",
	"KC_B",
	"KC_C",
	"KC_D",
	"KC_E",
	"KC_F",
	"KC_G",
	"KC_H",
	"KC_I",
	"KC_J",
	"KC_K",
	"KC_L",
	"KC_M",
	"KC_N",
	"KC_O",
	"KC_P",
	"KC_Q",
	"KC_R",
	"KC_S",
	"KC_T",
	"KC_U",
	"KC_V",
	"KC_W",
	"KC_X",
	"KC_Y",
	"KC_Z",
	"KC_1",
	"KC_2",
	"KC_3",
	"KC_4",
	"KC_5",
	"KC_6",
	"KC_7",
	"KC_8",
	"KC_9",
	"KC_0",
	"KC_ENTER",
	"KC_ESCAPE",
	"KC_BACKSPACE",
	"KC_TAB",
	"KC_SPACE",
	"KC_MINUS",
	"KC_EQUAL",
	"KC_LBRACKET",
	"KC_RBRACKET",
	"KC_BSLASH",
	"KC_SCOLON",
	"KC_QUOTE",
	"KC_GRAVE",
	"KC_COMMA",
	"KC_DOT",
	"KC_SLASH",
	"KC_CAPSLOCK",
	"KC_F1",
	"KC_F2",
	"KC_F3",
	"KC_F4",
	"KC_F5",
	"KC_F6",
	"KC_F7",
	"KC_F8",
	"KC_F9",
	"KC_F10",
	"KC_F11",
	"KC_F12",
	"KC_PRINT",
	"KC_SCROLLLOCK",
	"KC_PAUSE",
	"KC_INSERT",
	"KC_HOME",
	"KC_END",
	"KC_PAGEUP",
	"KC_PGDOWN",
	"KC_RIGHT",
	"KC_LEFT",
	"KC_DOWN",
	"KC_UP",
	"KC_NUMLOCK",
	"KC_KP_SLASH",
	"KC_KP_ASTERISK",
	"KC_KP_MINUS",
	"KC_KP_PLUS",
	"KC_KP_ENTER",
	"KC_KP_1",
	"KC_KP_2",
	"KC_KP_3",
	"KC_KP_4",
	"KC_KP_5",
	"KC_KP_6",
	"KC_KP_7",
	"KC_KP_8",
	"KC_KP_9",
	"KC_KP_0",
	"KC_KP_DOT",
	"KC_KP_EQUAL",
	"KC_KP_COMMA",
}

var MODIFIER_KEYCODES = []string{
	"KC_LCTL",
	"KC_LSFT",
	"KC_LALT",
	"KC_LGUI",
	"KC_RCTL",
	"KC_RSFT",
	"KC_RALT",
	"KC_RGUI",
}

var LAYER_KEYCODES = []string{
	"MO(1)",
	"MO(2)",
	"MO(3)",
	"TG(1)",
	"TG(2)",
	"TG(3)",
	"LT(1,KC_SPACE)",
	"LT(2,KC_SPACE)",
	"DF(0)",
	"DF(1)",
	"DF(2)",
	"TT(1)",
	"TT(2)",
}

var MEDIA_KEYCODES = []string{
	"KC_MUTE",
	"KC_VOLU",
	"KC_VOLD",
	"KC_MPLY",
	"KC_MNXT",
	"KC_MPRV",
	"KC_STOP",
	"KC_EJCT",
}

var SPECIAL_KEYCODES = []string{
	"RESET",
	"EEP_RST",
	"BL_TOGG",
	"BL_INC",
	"BL_DEC",
	"BL_STEP",
	"RGB_TOG",
	"RGB_HUI",
	"RGB_HUD",
	"RGB_SAI",
	"RGB_SAD",
	"RGB_VAI",
	"RGB_VAD",
	"RGB_SPI",
	"RGB_SPD",
	"RGB_MOD",
	"RGB_RMOD",
}

var MOD_TAP_KEYCODES = []string{
	"MT(KC_LCTL,KC_ESC)",
	"MT(KC_RCTL,KC_ESC)",
	"MT(KC_LSFT,KC_ESC)",
	"MT(KC_RSFT,KC_ESC)",
	"LCTL_T(KC_ESC)",
	"LSFT_T(KC_ESC)",
	"LALT_T(KC_ESC)",
	"LGUI_T(KC_ESC)",
	"RCTL_T(KC_ESC)",
	"RSFT_T(KC_ESC)",
	"RALT_T(KC_ESC)",
	"RGUI_T(KC_ESC)",
}

var ALL_KEYCODES []string

func init() {
	ALL_KEYCODES = append(ALL_KEYCODES, BASIC_KEYCODES...)
	ALL_KEYCODES = append(ALL_KEYCODES, MODIFIER_KEYCODES...)
	ALL_KEYCODES = append(ALL_KEYCODES, LAYER_KEYCODES...)
	ALL_KEYCODES = append(ALL_KEYCODES, MEDIA_KEYCODES...)
	ALL_KEYCODES = append(ALL_KEYCODES, SPECIAL_KEYCODES...)
	ALL_KEYCODES = append(ALL_KEYCODES, MOD_TAP_KEYCODES...)
}

type KeycodeCategory struct {
	Name     string
	Keycodes []string
}

var KEYCODE_CATEGORIES = []KeycodeCategory{
	{"Basic", BASIC_KEYCODES},
	{"Modifiers", MODIFIER_KEYCODES},
	{"Layers", LAYER_KEYCODES},
	{"Media", MEDIA_KEYCODES},
	{"Special", SPECIAL_KEYCODES},
	{"Mod-Tap", MOD_TAP_KEYCODES},
}
