name: Build Keyboards

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix script permissions
        run: chmod +x util/list_keyboards.sh

      - name: Install/Upgrade QMK CLI
        run: pip install qmk --upgrade --force-reinstall --break-system-packages

      - name: Build ${{ matrix.keyboard.name }}:${{ matrix.keyboard.keymap }}
        run: make ${{ matrix.keyboard.name }}:${{ matrix.keyboard.keymap }} SKIP_GIT=yes SKIP_QMK_CHECK=yes

    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - { name: crkbd, keymap: zonekeyboards }
          - { name: sofle, keymap: zonekeyboards }
          - { name: lily58, keymap: zonekeyboards }
          - { name: lily58zk, keymap: zonekeyboards }
          - { name: reviung41, keymap: zonekeyboards }
          - { name: zkpad, keymap: default }